# Generated by Django 5.2.10 on 2026-02-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
